
* Cointegration

** 研究变量之间的协整关系，对研究经济问题的定量分析有着重要的意义：
    平稳序列（stationary series）是基本上不存在趋势的序列。这类序列中的各观察值基本上在某个固定的水平上波动，虽然在不同的时间段波动的程度不同，但并不存在某种规律，其波动可以看成是随机的。
　　（1）定量描述经济规律：协整表明尽管两个序列虽然都是非平稳的I(1)，但两者的某个线性组合却可能存在一种平稳关系。这种平稳关系，对于研究经济学中变量之间存在的稳定的经济规律的定量描述具有很重要的意义。研究变量之间的协整关系，就等于研究变量之间的定量规律。

　　（2）避免伪回归。如果一组非平稳时间序列不存在协整关系，则根据它们构造的回归模型就可能是伪回归。伪回归模型尽管有很高的R2值和t值，但OLS的参数估计值却是非一致的（这种结果看上去很好但却是毫无意义的回归，被格兰杰（Granger）和纽博尔德（Newbold）称为伪回归）。

　　一般在时间序列的回归中，DW值很低而R2却很高，就应怀疑存在伪回归的可能。如果建立模型前，对变量之间的协整关系进行了检验，证明了它们是协整的，那么所建立的回归模型则可以避免伪回归。所以，对变量之间的协整检验是避免伪回归的事先预防。

　　（3）区分变量之间的长期均衡关系和短期波动关系。长期均衡关系就是指两个时间序列共同漂移的方式。短期波动关系是指yt对长期趋势的偏离\triangleyt与xt对长期趋势的偏离\trianglext之间的关系。误差修正模型便是一种能同时考虑变量之间这两种关系的一种模型。


** 我的理解：
1. 如果一个序列如果是一个不存在趋势的序列，那么他是一个平稳序列（可以用ADF算法检验https://nwfsc-timeseries.github.io/atsa-labs/sec-boxjenkins-aug-dickey-fuller.html）
2. 如果这个序列不是平稳序列，但是经过一次差分之后平稳了，那么他是一阶平稳序列
3. 现在有两个序列，我们要对他们进行相关性检验（不是相似性。。这个怎么区分就很迷惑）
4. 首先要对他们进行一节差分，如果都是平稳的话就进行下一步，否则没必要检测协整性了
5. 对两条数据进行协整检验，如果这两条数据的某种线性组合是平稳的，那么说这两条数据是协整的。
（之所以要先进行差分平稳性检测是因为，协整检验第一步是要将两个序列进行线性拟合OLS，如果两条序列不是一阶单整的话，构造出来的回归可能是伪回归，为回归可能没有意义）
